### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by gustavomf-cit** [snyk/snyk-python-plugin#32]
- `node -v`: v4.2.6
- `npm -v`: 3.5.2
- `snyk -v`: 1.71.0
- Command run:
snyk test

### Expected behaviour
accept packages from pip3

### Actual behaviour
accept only pip2 packages

### Steps to reproduce

sudo apt install -y npm
sudo npm install -g snyk
cd ~/projects
 
 
machine:~/project$ snyk test
Please run `pip install -r requirements.txt`
 
machine:~/project$ sudo pip2 install -r requirements.txt

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by dgur1n** [comment]
I have the same behaviour with 1.85.0
Any updates here? Will it be implemented? Any answer would be appreciated.

Thanks!

**Comment by gablaxian** [comment]
Hi @gustavomf-cit @dgur1n 

Please forgive my limited knowledge of Python. I mostly work in Node myself, but I'd like to help get to the bottom of this issue.

Can you try running `snyk test --command=python3` on your repos and see if that works?

Otherwise I think the alternative is to be in a python 3 environment first. I ran some tests locally on a python3/pip3 project and these are my steps:

`python3 -m venv my_env`
`source my_env/bin/activate`

Once I was in that env I switched to my project and ran:

`pip3 install -r requirements.txt`
`snyk test`

The result of the test showed the vulnerabilities I was expecting.

Let me know if either of the above methods works for you.

**Comment by gustavomf-cit** [comment]
after I updated from  1.71.0 to 1.90.0 is working fine

`snyk test --command=python3` 

✓ Tested 24 dependencies for known vulnerabilities, no vulnerable paths found.
